#! /bin/sh

cat /dev/cmux3 /home/root/hello &
sleep 1
echo -e "\n"
chat -V -s '' 'at+cpin?' '' > /dev/cmux3 < /dev/cmux3
sleep 2
echo -e "\n"
chat -V -s '' 'AT+CREG?' '' > /dev/cmux3 < /dev/cmux3
sleep 2
echo -e "\n"
chat -V -s '' 'at+csq' '' > /dev/cmux3 < /dev/cmux3
sleep 2
killall cat
exit 0

