#!/bin/bash

#touch new
#cat /sys/bus/i2c/devices/0-0050/eeprom | hexdump -C | grep 00001000 | awk '{print $18}' > new
#cut -c2-10 new > /usr/share/status/EEPROM-data
#cat /sys/bus/i2c/devices/0-0050/eeprom | hexdump -C | grep 00001010 | awk '{print $18}' > new
#cut -c3-10 new >> /usr/share/status/EEPROM-data
#cut -c3-10 new > /usr/share/status/EEPROM-serial
#rm new
machine_status=`cat /usr/share/status/MACHINEID_status`
if [ $machine_status -eq '1' ]
then
	chattr -i /media/sdcard/MACHINEid.enc;openssl aes-256-cbc -d -a -in /media/sdcard/MACHINEid.enc -out /tmp/mid -k "technovates";chattr +i /media/sdcard/MACHINEid.enc
	chattr -i /media/sdcard/MACHINEserial.enc;openssl aes-256-cbc -d -a -in /media/sdcard/MACHINEserial.enc -out /tmp/mserial -k "technovates";chattr +i /media/sdcard/MACHINEid.enc
	machineid=`cat /tmp/mid` 
	machineserial=`cat /tmp/mserial`
	echo $machineid > /usr/share/status/EEPROM-data
	echo $machineserial >> /usr/share/status/EEPROM-data
	echo $machineid > /usr/share/status/EEPROM-serial
	rm /tmp/mid
	rm /tmp/mserial
else
	eepromtool -r -s 0 > /usr/share/status/EEPROM-data
	eepromtool -r -s 1 >> /usr/share/status/EEPROM-data
	eepromtool -r -s 1 > /usr/share/status/EEPROM-serial
fi
