#!/bin/bash
#echo $1....... > /usr/share/status/bbb-eeprom.dump
#echo $2........ >> /usr/share/status/bbb-eeprom.dump
#cat /usr/share/status/bbb-eeprom.dump > /sys/bus/i2c/devices/0-0050/eeprom
machine_status=`cat /media/sdcard/MACHINEID_status`
if [ $machine_status -eq '1' ]
then
	chattr -i /media/sdcard/MACHINEid.enc
	chattr -i /media/sdcard/MACHINEserial.enc
	echo $1 > /tmp/mid 
	echo $2 > /tmp/mserial
	openssl aes-256-cbc -a -salt -in /tmp/mid -out /media/sdcard/MACHINEid.enc -k "technovates"
	chattr +i /media/sdcard/MACHINEid.enc
	openssl aes-256-cbc -a -salt -in /tmp/mserial -out /media/sdcard/MACHINEserial.enc -k "technovates"
	chattr +i /media/sdcard/MACHINEserial.enc
	rm /tmp/mid;rm /tmp/mserial;
else
	eepromtool -w -s 0 $1
	eepromtool -w -s 1 $2
fi
