#!/bin/sh

set -e

start()
{
  if [ -f /etc/profile.d/tslib.sh ]; then
     source /etc/profile.d/tslib.sh
  fi

  if [ ! -f /etc/pointercal ]; then
     /usr/bin/ts_calibrate
  fi

  echo "Starting Demo..."
  export QWS_MOUSE_PROTO=Tslib:${TSLIB_TSDEVICE}
  /opt/sdk/resources/sdk.sh
}

stop()
{
  echo "Killing Application Launcher..."
  killall ClanCor_HHC
}


case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  *)
  ;;
esac
